// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    public class State__Update_639985b94e
    {
        private Mock<IUpdatable> _mockUpdatable;
        
        [SetUp]
        public void Setup()
        {
            _mockUpdatable = new Moq.Mock<IUpdatable>();
        }

        [Test]
        public void Update_StateCalled_CallsUpdateOnDependencies()
        {
            var state = new StateImplementation(_mockUpdatable.Object);
            state._Update(0.5f);

            _mockUpdatable.Verify(updatable => updatable.Update(0.5f), Times.Once());
        }

        [Test]
        public void Update_PositiveDeltaTime_CallsUpdateOnDependencies()
        {
            var state = new StateImplementation(_mockUpdatable.Object);
            state._Update(10.0f);
            
            _mockUpdatable.Verify(updatable => updatable.Update(10.0f), Times.Once());
        }

        [Test]
        public void Update_NegativeDeltaTime_CallsUpdateOnDependencies()
        {
            var state = new StateImplementation(_mockUpdatable.Object);
            state._Update(-5.0f);
            
            _mockUpdatable.Verify(updatable => updatable.Update(-5.0f), Times.Once());
        }
        
        [Test]
        public void Update_ZeroDeltaTime_CallsUpdateOnDependencies()
        {
            var state = new StateImplementation(_mockUpdatable.Object);
            state._Update(0.0f);
            
            _mockUpdatable.Verify(updatable => updatable.Update(0.0f), Times.Once());
        } 
    }
}
