// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using Moq;
using FiniteStateMachine;

namespace FiniteStateMachine.Tests
{
    [TestFixture]
    public class State__Update_639985b94eTests
    {
        private MockRepository mockRepository;
        private Mock<State__Update_639985b94e> mockStateUpdate;

        [SetUp]
        public void SetUp()
        {
            this.mockRepository = new MockRepository(MockBehavior.Strict);
            this.mockStateUpdate = this.mockRepository.Create<State__Update_639985b94e>();
        }

        [TearDown]
        public void TearDown()
        {
            this.mockRepository.VerifyAll();
        }

        [Test]
        public void Test_Update_PositiveDeltaTime()
        {
            float deltaTime = 0.2f;
            this.mockStateUpdate.Setup(m => m._Update(deltaTime));
            this.mockStateUpdate.Object._Update(deltaTime);
        }

        [Test]
        public void Test_Update_ZeroDeltaTime()
        {
            float deltaTime = 0.0f;
            this.mockStateUpdate.Setup(m => m._Update(deltaTime));
            this.mockStateUpdate.Object._Update(deltaTime);
        }

        [Test]
        public void Test_Update_NegativeDeltaTime()
        {
            float deltaTime = -0.2f;
            Assert.Throws<ArgumentException>(() => this.mockStateUpdate.Object._Update(deltaTime));
        }
    }
}
