// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;
using System;

namespace FiniteStateMachine.Test
{
    public class FiniteStateChangeEventArgsTests
    {
        [TestFixture]
        public class Constructor_Should
        {
            [Test]
            public void Assign_RequestedState()
            {
                //Arrange
                var state = StateType.SomeState;

                //Act
                var eventArgs = new FiniteStateChangeEventArgs(state);

                //Assert
                Assert.AreEqual(state, eventArgs.RequestedType);
            }
            
            [Test]
            public void Throw_When_RequestedState_Is_Null()
            {
                //Arrange
                StateType state = null;

                //Act
                TestDelegate action = () => new FiniteStateChangeEventArgs(state);

                //Assert
                Assert.Throws<ArgumentNullException>(action);
            }
        }
    }
}
