// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using System;
using NUnit.Framework;
using Moq;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
   public class State__End_5b00770643Tests
   {
       private Mock<State__End_5b00770643> _mockState;

       [SetUp]
       public void Setup()
       {
           _mockState = new Mock<State__End_5b00770643>();
       }

       [Test]
       public void Test_End_WhenCalled()
       {
           // Arrange 
           _mockState.Setup(s => s._End()).Verifiable();

           // Act
           _mockState.Object._End();

           // Assert
           _mockState.Verify(s => s._End(), Times.Once);
       }

       [Test]
       public void Test_End_ThrowsException()
       {
           // Arrange 
           _mockState.Setup(s => s._End()).Throws(new Exception("Test Exception"));

           // Act & Assert
           Assert.Throws<Exception>(() => _mockState.Object._End());
       }
   }
}
