// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using Moq;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    public class State__End_5b00770643Test
    {
        private Mock<State__End_5b00770643> _mockStateEnd5b00770643;

        [SetUp]
        public void Setup()
        {
            _mockStateEnd5b00770643 = new Mock<State__End_5b00770643>();
        }

        [Test]
        public void _End_MethodShouldCallEndOnce()
        {
            // Arrange
            _mockStateEnd5b00770643.Setup(end => end._End());
            
            // Act
            _mockStateEnd5b00770643.Object._End();

            // Assert
            _mockStateEnd5b00770643.Verify(end => end.End(), Times.Once);
        }

        [Test]
        public void _End_MethodShouldThrowWhenFailedToExecute()
        {
            // Arrange
            _mockStateEnd5b00770643.Setup(end => end._End()).Throws<InvalidOperationException>();

            // Assert
            Assert.Throws<InvalidOperationException>(() => _mockStateEnd5b00770643.Object._End());
        }
    }
}
