// Code generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k
using NUnit.Framework;
using Moq;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    public class FiniteStateBeganEventArgsTests
    {
        private FiniteStateBeganEventArgs _finiteStateBeganEventArgs;
        private Mock<IStateType> _stateType; // Change to an interface or a class 

        [SetUp]
        public void Setup()
        {
            _stateType = new Mock<IStateType>(); // Setup the mock object
            _finiteStateBeganEventArgs = new FiniteStateBeganEventArgs(_stateType.Object);
        }

        [Test]
        public void FiniteStateBeganEventArgs_Constructor_SetsTypePropertySuccessfully()
        {
            Assert.AreEqual(_stateType.Object, _finiteStateBeganEventArgs.Type);
        }

        [Test]
        public void FiniteStateBeganEventArgs_Constructor_InvalidState_ThrowsArgumentOutOfRangeException()
        {
            Assert.Throws<ArgumentOutOfRangeException>(() => new FiniteStateBeganEventArgs(null));
        }
    }
}

public interface IStateType { } // Declare IStateType interface
