// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    public class FiniteStateBeganEventArgs_FiniteStateBeganEventArgs_9169a2778c
    {
        [TestFixture]
        public class Tests
        {
            private FiniteStateBeganEventArgs _finiteStateBeganEventArgs;

            [SetUp]
            public void Setup()
            {
                _finiteStateBeganEventArgs = new FiniteStateBeganEventArgs(StateType.Start);
            }
            
            [Test]
            public void Constructor_Success_AssignsCorrectType()
            {
                Assert.AreEqual(StateType.Start, _finiteStateBeganEventArgs.Type);
            }

            [Test]
            public void Constructor_Error_AssignsIncorrectType()
            {
                Assert.AreNotEqual(StateType.End, _finiteStateBeganEventArgs.Type);
            }
        }
    }
}
