// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class FiniteStateBeganEventArgs_FiniteStateBeganEventArgs_9169a2778c
    {
        [Test]
        public void Should_SetType_When_ValidStatePassed()
        {
            // Arrange
            var state = new StateType();

            // Act
            var args = new FiniteStateBeganEventArgs(state);

            // Assert
            Assert.AreSame(state, args.Type);
        }

        [Test]
        public void Should_ThrowArgumentNullException_When_NullStatePassed()
        {
            // Arrange, Act, Assert
            Assert.Throws<ArgumentNullException>(() => new FiniteStateBeganEventArgs(null));
        }
        
    }
}
