// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class StateMachine_Initialize_99e1f35a6a
    {
        //Arrange
        private Mock<IStateMachine> _mockStateMachine;

        [SetUp]
        public void Setup()
        {
            _mockStateMachine = new Mock<IStateMachine>();
        }

        [Test]
        public void Initialize_ValidCall_AssertSuccess()
        {
            //Act
            _mockStateMachine.Object.Initialize();

            //Assert
            _mockStateMachine.Verify(x => x.Initialize(), Times.Once);
        }

        [Test]
        public void Initialize_MultipleCalls_AssertFail()
        {
            //Act
            _mockStateMachine.Object.Initialize();
            _mockStateMachine.Object.Initialize();

            //Assert
            _mockStateMachine.Verify(x => x.Initialize(), Times.Once);
        }
    }
}
