// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using NSubstitute;
using FiniteStateMachine;

namespace FiniteStateMachine.Tests
{
    [TestFixture]
    public class StateBase__End_3643a6cf0dTests
    {
        private IFiniteStateMachine _finiteStateMachine;
        private StateBase__End_3643a6cf0d _stateBase;

        [SetUp]
        public void SetUp()
        {
            _finiteStateMachine = Substitute.For<IFiniteStateMachine>();
            _stateBase = new StateBase__End_3643a6cf0d(_finiteStateMachine);
        }

        [Test]
        public void _End_StateEnds_FiniteStateEndedEventIsFired()
        {
            bool wasEventFired = false;
            _finiteStateMachine.OnStateEnded += (sender, args) => wasEventFired = true;

            _stateBase._End();

            Assert.IsTrue(wasEventFired);
        }

        [Test]
        public void _End_StateEnds_StateKeyIsCorrectInEventArgs()
        {
            var expectedStateKey = _stateBase.StateKey;
            FiniteStateEndedEventArgs eventArgs = null;
            _finiteStateMachine.OnStateEnded += (sender, args) => eventArgs = args;

            _stateBase._End();

            Assert.AreEqual(expectedStateKey, eventArgs.StateKey);
        }
    }
}
