// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using Moq;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class StateMachine_Update_73a5496b2c
    {
        private Mock<IState> stateMock;
        private StateMachine stateMachine;

        [SetUp]
        public void Setup()
        {
            stateMock = new Mock<IState>();
            stateMachine = new StateMachine();
        }

        [Test]
        public void Update_StateIsNull_NoUpdateCalled()
        {
            stateMachine.Update(1.0f);

            stateMock.Verify(m => m._Update(It.IsAny<float>()), Times.Never);
        }

        [Test]
        public void Update_StateIsNotNull_UpdateCalled()
        {
            stateMachine.SetState(stateMock.Object);
            stateMachine.Update(2.0f);

            stateMock.Verify(m => m._Update(2.0f), Times.Once);
        }
    }
}
