// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using Moq;

namespace FiniteStateMachine.Test 
{
    public class StateBase__Update_8c1484250f
    {
        private Mock<StateBase__Update_8c1484250f> _stateBaseUpdateMock;
        private const float DeltaTime = 0.1f;
        private const float NegativeDeltaTime = -0.1f;

        [SetUp]
        public void Setup()
        {
            _stateBaseUpdateMock = new Mock<StateBase__Update_8c1484250f>(){ CallBase = true };
        }

        [Test]
        public void Update_CalledWithPositiveDt_InvokesBaseUpdateWithSameValue()
        {
            _stateBaseUpdateMock.Object._Update(DeltaTime);
            _stateBaseUpdateMock.Verify(s => s.Update(DeltaTime), Times.Once);
        }

        [Test]
        public void Update_CalledWithNegativeDt_InvokesBaseUpdateWithSameValue()
        {
            _stateBaseUpdateMock.Object._Update(NegativeDeltaTime);
            _stateBaseUpdateMock.Verify(s => s.Update(NegativeDeltaTime), Times.Once);
        }

        [TearDown]
        public void TearDown()
        {
            _stateBaseUpdateMock = null;
        }
    }
}
