// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using System;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class FiniteStateMachine_FiniteStateMachine_4ac7eeddda
    {
        private FiniteStateMachine _finiteStateMachine;

        [SetUp]
        public void Setup()
        {
            _finiteStateMachine = new FiniteStateMachine();
        }

        [Test]
        public void Constructor_SuccessfulCreation()
        {
            // Here, we simply assert that the object created successfully
            // The returned object should not be null
            Assert.That(_finiteStateMachine, Is.Not.Null);
        }

        // TODO: Your additional tests go here...
        
        [Test]
        public void Constructor_CorrectType()
        {
            // Check that the constructor creates an instance of the correct type.
            Assert.That(_finiteStateMachine, Is.InstanceOf<FiniteStateMachine>());
        }        

        [Test]
        public void Constructor_NewInstance()
        {
            // Check that a new instance is not the same as the previous instance.
            FiniteStateMachine anotherStateMachine = new FiniteStateMachine();
            Assert.AreNotSame(_finiteStateMachine, anotherStateMachine);
        }        
    }
}
