// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using Moq;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class State_State_f11a4f0491Test
    {
        private Mock<StateMachine<int>> _mockFsm;

        [SetUp]
        public void SetUp()
        {
            _mockFsm = new Mock<StateMachine<int>>();
        }

        [Test]
        public void Should_Set_StateMachine_And_StateKey_On_Successful_Creation()
        {
            var testStateKey = 123;
            var testState = new State<int>(_mockFsm.Object, testStateKey);

            Assert.IsNotNull(testState.StateMachine);
            Assert.AreEqual(testStateKey, testState.StateKey);
        }

        [Test]
        public void Should_Throw_ArgumentNullException_If_FSM_Is_Null()
        {
            Assert.Throws<ArgumentNullException>(() => new State<int>(null, 123));
        }

        [TearDown]
        public void TearDown()
        {
            _mockFsm = null;
        } 
    }
}
