// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using System;
using Moq;

namespace FiniteStateMachine.Test
{
    public class State_State_Key_Tests
    {
        private State<int> _state;

        [SetUp]
        public void Setup()
        {
            var fsmMock = new Mock<StateMachine<int>>();
            _state = new State<int>(fsmMock.Object, 1);
        }

        [Test]
        public void Constructor_Should_Set_StateMachine()
        {
            var fsmMock = new Mock<StateMachine<int>>();
            var state = new State<int>(fsmMock.Object, 1);

            Assert.IsInstanceOf<StateMachine<int>>(state.StateMachine);
        }

        [Test]
        public void Constructor_Should_Set_StateKey()
        {
            var fsmMock = new Mock<StateMachine<int>>();
            var state = new State<int>(fsmMock.Object, 1);

            Assert.AreEqual(1, state.StateKey);
        }

        [Test]
        public void Constructor_Should_Throw_ArgumentNullException_If_StateMachine_Null()
        {
            Assert.Throws<ArgumentNullException>(() => new State<int>(null, 1));
        }
    }
}
