// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;
using System;

namespace FiniteStateMachine.Test
{
    public class FiniteStateEndedEventArgsTests
    {
        [Test]
        public void Constructor_ShouldAssignType_WhenCalledWithValidStateType()
        {
            // Arrange
            StateType input = StateType.ValidState;

            // Act
            FiniteStateEndedEventArgs endedEventArgs = new FiniteStateEndedEventArgs(input);

            // Assert
            Assert.AreEqual(input, endedEventArgs.Type);
        }

        [Test]
        public void Constructor_ShouldThrowArgumentException_WhenCalledWithInvalidStateType()
        {
            // Arrange
            StateType input = (StateType)999; // Assuming 999 is not a valid StateType enum value

            // Act & Assert
            Assert.Throws<ArgumentException>(() => new FiniteStateEndedEventArgs(input));
        }
    }
}
