// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;

namespace FiniteStateMachine.Test 
{
    [TestFixture]
    public class FiniteStateEndedEventArgsTest 
    {
        [Test]
        public void FiniteStateEndedEventArgs_WithValidState_SetsTypeCorrectly()
        {
            StateType expectedState = StateType.Valid;
            
            FiniteStateEndedEventArgs eventArgs = new FiniteStateEndedEventArgs(expectedState);
            
            Assert.AreEqual(expectedState, eventArgs.Type);
        }
        
        [Test]
        public void FiniteStateEndedEventArgs_WithInvalidState_SetsTypeCorrectly()
        {
            StateType expectedState = StateType.Invalid;
            
            FiniteStateEndedEventArgs eventArgs = new FiniteStateEndedEventArgs(expectedState);
            
            Assert.AreEqual(expectedState, eventArgs.Type);
        }
    }        
}
