// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using Moq;

namespace FiniteStateMachine.Test
{
    public class FiniteStateMachine_Initialize_df35803478
    {
        Mock<YourObject> _mockObject;

        [SetUp]
        public void Setup()
        {
            _mockObject = new Mock<YourObject>();
        }

        [Test]
        public void Initialize_ValidCall_AssertsSuccessful()
        {
            // Arrange
            _mockObject.Setup(x => x.Initialize()).Verifiable();
            
            // Act
            _mockObject.Object.Initialize();

            // Assert
            _mockObject.Verify(x => x.Initialize(), Times.Once);
        }

        [Test]
        public void Initialize_DoubleCall_ThrowsException()
        {
            // Arrange
            _mockObject.Setup(x => x.Initialize()).Verifiable();
            
            // Act - Assert
            Assert.Throws<Exception>(() =>
            {
                _mockObject.Object.Initialize();
                _mockObject.Object.Initialize();
            });

            // Assert
            _mockObject.Verify(x => x.Initialize(), Times.Exactly(2));
        }

        [TearDown]
        public void Teardown()
        {
            _mockObject = null;
        }
    }
}
