// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using Moq;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class StateBase__Begin_1ebf58b534Test
    {
        private StateBase__Begin_1ebf58b534 _begin;
        
        [SetUp]
        public void SetUp()
        {
            _begin = new StateBase__Begin_1ebf58b534();
        }
    }
}
