// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    public class FiniteStateChangeEventArgs_FiniteStateChangeEventArgs_08e3fe74ea 
    {
        [Test]
        public void FiniteStateChangeEventArgs_WithNonNullArguments_CreatesObjectWithValues()
        {
            var requestedState = new StateType();
            var stateInfo = new StateInfo();

            var result = new FiniteStateChangeEventArgs(requestedState, stateInfo);

            Assert.That(result.RequestedType, Is.EqualTo(requestedState));
            Assert.That(result.StateInfo, Is.EqualTo(stateInfo));
        }

        [Test]
        public void FiniteStateChangeEventArgs_WithNullArguments_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new FiniteStateChangeEventArgs(null, new StateInfo()));
            Assert.Throws<ArgumentNullException>(() => new FiniteStateChangeEventArgs(new StateType(), null));
            Assert.Throws<ArgumentNullException>(() => new FiniteStateChangeEventArgs(null, null));
        }
    }
}
