// Test generated by RoostGPT for test MiniPythonProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using System.Collections.Generic;

namespace FiniteStateMachine.Test
{
    public class StateMachine_StateMachine_878571cb02
    {
        private StateMachine<int> _stateMachine;

        [SetUp]
        public void Setup()
        {
            _stateMachine = new StateMachine<int>();
        }

        [Test]
        public void Constructor_CreatesInstance_SetsInitialStatesToEmptyDictionary()
        {
            Assert.NotNull(_stateMachine);
            var dictType = _stateMachine.GetStates().GetType();
            Assert.AreEqual(typeof(Dictionary<int, State<int>>), dictType);
            Assert.IsEmpty(_stateMachine.GetStates());
        }
        
        [Test]
        public void Constructor_CreatesInstance_WhenInvokedMultipleTimes()
        {
            var anotherStateMachine = new StateMachine<int>();
            Assert.NotNull(anotherStateMachine);
            var dictType = anotherStateMachine.GetStates().GetType();
            Assert.AreEqual(typeof(Dictionary<int, State<int>>), dictType);
            Assert.IsEmpty(anotherStateMachine.GetStates());
        }

        [TearDown]
        public void Teardown()
        {
            _stateMachine = null;
        }
    }
}
